### ISSUE TITLE
[BUG] The feedback email is not supported

### ISSUE THREAD

**Issue by desbest** [SynQApp/Extension#55]
The email mentioned on your [cookie policy](https://www.synqapp.io/cookie-policy) and your [privacy policy](https://www.synqapp.io/privacy-policy), uses the `support@` when your github account uses the `info@` email address.

It looks like your website is using an outdated or incorrectly spelt email address. Can this be fixed?

**Comment by mkossoris** [comment]
Thanks for pointing this out - the email has been update with info@synqapp.io on the website!
