### ISSUE TITLE
[BUG] Stuck on choose platform

### ISSUE THREAD

**Issue by CashierNub** [SynQApp/Extension#56]
**Describe the bug**
when i click the extension, i get stuck on choose platform

**To Reproduce**
1. Go to 'the extension'
2. Click on 'the extension'
3. stuck on choose platform

**Expected behavior**
stuck on choose platform

**Screenshots**

**Device (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 123.0.6312.86 (Official Build) (64-bit)

**Additional context**
stuck on "choose a platform"

**Comment by mkossoris** [comment]
Hey there, thanks for the report. I can't seem to repro this issue with just the steps you provided. What happens when you click one of the "Continue with" buttons? Also could you tell me which music service you're trying to use it with?

**Comment by mkossoris** [comment]
Closing as there has been no additional info provided and I cannot repro the issue on any browser/OS combo.
